---
title: "Project Sandbox"
author: "Hung Tran, Linh Ta"
date: "6/17/2020"
output: pdf_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# This file is a sandbox. It should contain explorations with the dataset, along with useful comments for each exploration.

# It is important that each sanbox section should be documented of its purpose and methods, and should not spam the whole document (use filter, head, tail, etc.).

# The dataset of info on colleges listed
(college_ds = read.csv("data/project_data_.csv"))

# Creating blocks with include=FALSE can make space to leave comments per section, like this one.
```

```{r, visualize college_ds}
# See the dataset of the best and worst 10 rankings of colleges
head(college_ds, 10)
tail(college_ds, 10)

# Plot the dataset of median SAT and median ACT per college into the reported early career earnings in that college.
# SAT score has a much higher range than ACT, so the graph looks more "continuous"
scatter.smooth(college_ds$Median.SAT, (college_ds$Early.career.earnings)^(1/2))
# ACT score has less range, so the graph looks "discrete"
scatter.smooth(college_ds$Median.ACT, (college_ds$Early.career.earnings)^(1/2))

scatter.smooth(college_ds$Median.SAT, (college_ds$Early.career.earnings))
scatter.smooth(college_ds$Median.ACT, (college_ds$Early.career.earnings))
```

```{r, filter rows with both median SAT and median ACT are NAs}
# Get rows that have no NA, or only one of SAT, ACT is NA. Omit if both is NA.
college_ds_predict = subset(college_ds, !is.na(Median.SAT) | !is.na(Median.ACT))
# college_ds_no_na = subset(college_ds, !(is.na(Median.SAT) & is.na(Median.ACT)))
# Omit the row where ANY column of (SAT, ACT) is NA.
college_ds_no_na = subset(college_ds, !is.na(Median.SAT) & !is.na(Median.ACT))
corr_c_ds_act = cor(college_ds_no_na$Median.ACT, college_ds_no_na$Early.career.earnings)
corr_c_ds_sat = cor(college_ds_no_na$Median.SAT, college_ds_no_na$Early.career.earnings)
```

```{r, predict NA ACT}
plot(college_ds_no_na$Median.SAT, college_ds_no_na$Median.ACT)
ACT_bounds = c(1, 36)
clamp <- function(x, bounds) {
  pmax(pmin(x, bounds[2]), bounds[1])
}
predict_ACT_lm = lm(Median.ACT ~ Median.SAT, data = college_ds_no_na)

# <not necessary>
act_pred = clamp(predict(predict_ACT_lm),ACT_bounds)
par(new = TRUE)
# Plot prediction on the trained dataset
points(college_ds_no_na$Median.SAT, act_pred, type = "l", col = "blue")
# </not necessary>
```

```{r}
# Plot ACT prediction from SAT from dataset with NAs
pred_ACT_na = clamp(round(predict(predict_ACT_lm, newdata = college_ds_predict)), ACT_bounds)
plot(college_ds_predict$Median.SAT, pred_ACT_na)
names(pred_ACT_na) <- NULL

# Intersection, but only take values that are NA in college_ds_predict
# How many NA?
sum(is.na(college_ds_predict$Median.ACT))
college_ds_predict$MedACT_pred = pred_ACT_na
college_ds_predict<- within(college_ds_predict, Median.ACT[is.na(Median.ACT)] <- MedACT_pred[is.na(Median.ACT)])
college_ds_predict$MedACT_pred <- NULL
# How many NA?
sum(is.na(college_ds_predict$Median.ACT))
```

```{r}
# Predict SAT based on ACT
predict_SAT_lm = lm(Median.SAT ~ Median.ACT, data = college_ds_no_na)
# Use the trained model to predict the datsset with NA
SAT_bounds = c(0,1600)
# predict, round to the nearest tenth, then clamp to the possible score
pred_SAT_na = clamp(round(predict(predict_SAT_lm, newdata= college_ds_predict)/10)*10, SAT_bounds)
college_ds_predict$MedSAT_pred = pred_SAT_na
# Intersection
college_ds_predict<- within(college_ds_predict, Median.SAT[is.na(Median.SAT)] <- MedSAT_pred[is.na(Median.SAT)])
college_ds_predict$MedSAT_pred <- NULL
```

```{r}
plot(college_ds$Est..price.2019.20.without.aid, college_ds$Early.career.earnings)
cor(college_ds$Est..price.2019.20.without.aid, college_ds$Early.career.earnings)
plot(college_ds$Est..price.2019.20.with.avg..grant, college_ds$Early.career.earnings)
cor(college_ds$Est..price.2019.20.with.avg..grant, college_ds$Early.career.earnings)
plot(college_ds$X..of.students.who.get.any.grants, college_ds$Early.career.earnings)
cor(college_ds$X..of.students.who.get.any.grants, college_ds$Early.career.earnings)
```



```{r}
# Assuming price w/ avg grant is price given that the student has any grant minus mean grant in that college
college_ds$Est_grant = college_ds$Est..price.2019.20.without.aid - college_ds$Est..price.2019.20.with.avg..grant

# Est_avg_price = Est_avg_price_no_aid * (1-prob_any_aid) + Est_avg_price_aid * (prob_any_aid)
college_ds$Est_avg_price = college_ds$Est..price.2019.20.with.avg..grant * college_ds$X..of.students.who.get.any.grants +
  college_ds$Est..price.2019.20.without.aid * (1-college_ds$X..of.students.who.get.any.grants)
college_ds_no_na$Est_avg_price = college_ds_no_na$Est..price.2019.20.with.avg..grant * college_ds_no_na$X..of.students.who.get.any.grants +
  college_ds_no_na$Est..price.2019.20.without.aid * (1-college_ds_no_na$X..of.students.who.get.any.grants)
plot(college_ds$Est_grant, college_ds$Early.career.earnings)
cor(college_ds$Est_grant, college_ds$Early.career.earnings)
# 0.4905114 (college_ds$Est_avg_price)
trans_avg_price = (college_ds$Est_avg_price)
# 0.4905114 (log(college_ds$Early.career.earnings))
trans_early_career = (log(college_ds$Early.career.earnings))
scatter.smooth(trans_avg_price, trans_early_career)
cor(trans_avg_price, trans_early_career)

```

```{r}
# ^(1/1,95)
# [1] 0.7101986
# [1] 0.6852481
trans_early_career_earnings = (college_ds_no_na$Early.career.earnings)^(1/2)
x_trans <- function(x) {
  return((x))
}
# SAT score has a much higher range than ACT, so the graph looks more "continuous"
scatter.smooth(x_trans(college_ds_no_na$Median.SAT), trans_early_career_earnings)
# ACT score has less range, so the graph looks "discrete"
scatter.smooth(x_trans(college_ds_no_na$Median.ACT), trans_early_career_earnings)

scatter.smooth(x_trans(college_ds_no_na$Median.SAT), (college_ds_no_na$Early.career.earnings))
scatter.smooth(x_trans(college_ds_no_na$Median.ACT), (college_ds_no_na$Early.career.earnings))

# SAT score has a much higher range than ACT, so the graph looks more "continuous"
cor(x_trans(college_ds_no_na$Median.SAT), trans_early_career_earnings)
# ACT score has less range, so the graph looks "discrete"
cor(x_trans(college_ds_no_na$Median.ACT), trans_early_career_earnings)

cor(x_trans(college_ds_no_na$Median.SAT), (college_ds_no_na$Early.career.earnings))
cor(x_trans(college_ds_no_na$Median.ACT), (college_ds_no_na$Early.career.earnings))

college_ds_no_na$score_ratio = (college_ds_no_na$Median.ACT-min(college_ds_no_na$Median.ACT))/
  (college_ds_no_na$Median.SAT - min(college_ds_no_na$Median.SAT))

scatter.smooth(x_trans(college_ds_no_na$score_ratio), trans_early_career_earnings)
cor(x_trans(college_ds_no_na$score_ratio), trans_early_career_earnings)

scatter.smooth(x_trans(college_ds_no_na$score_ratio), college_ds_no_na$Early.career.earnings)
cor(x_trans(college_ds_no_na$score_ratio), college_ds_no_na$Early.career.earnings)

hist((college_ds$X..of.students.who.get.any.grants)^2.1)
```

```{r}
lg.SAT_ece = lm(college_ds_no_na$Early.career.earnings ~ college_ds_no_na$Median.SAT)
# summary(lg.SAT_ece)
lg.ACT_ece = lm(college_ds_no_na$Early.career.earnings ~ college_ds_no_na$Median.ACT)
# summary(lg.ACT_ece)

plot(college_ds_no_na$Median.SAT, college_ds_no_na$Early.career.earnings, xlab = "Median SAT score", ylab = "Early career earning (* $10^4)")
par(new = FALSE)
pred_sat_ece = predict(lg.SAT_ece)
points(x = college_ds_no_na$Median.SAT, y = pred_sat_ece, type = "l", col = "red", xlab = "Median SAT score", ylab = "Early career earning (* $10^4)")

plot(college_ds_no_na$Median.ACT, college_ds_no_na$Early.career.earnings, xlab = "Median ACT score", ylab = "Early career earning (* $10^4)")
par(new = FALSE)
pred_act_ece = predict(lg.ACT_ece)
points(x = college_ds_no_na$Median.ACT, y = pred_act_ece, type = "l", col = "red", xlab = "Median ACT score", ylab = "Early career earning (* $10^4)")

summary(lg.SAT_ece)
summary(lg.ACT_ece)
lg.SAT_ACT_ece = lm(college_ds_no_na$Early.career.earnings ~ college_ds_no_na$Median.ACT + college_ds_no_na$Median.SAT)
summary(lg.SAT_ACT_ece)
lg.scaled_SAT_ACT_ece = lm(college_ds_no_na$Early.career.earnings ~ (pred_act_ece) + pred_sat_ece)
summary(lg.scaled_SAT_ACT_ece)
plot(college_ds_no_na$Early.career.earnings, resid(lg.scaled_SAT_ACT_ece))
plot(college_ds_no_na$Est_avg_price, resid(lg.scaled_SAT_ACT_ece))
#plot(college_ds_no_na, resid(lg.scaled_SAT_ACT_ece))
```


```{r}
scatter.smooth(college_ds_no_na$Est_avg_price, college_ds_no_na$Median.SAT)
scatter.smooth(college_ds_no_na$Est_avg_price, college_ds_no_na$Median.ACT)
lg.avg_price_SAT = lm(college_ds_no_na$Est_avg_price ~ college_ds_no_na$Median.SAT)
summary(lg.avg_price_SAT)

cor(college_ds_no_na$Est_avg_price, college_ds_no_na$Median.SAT)
cor(college_ds_no_na$Est_avg_price, college_ds_no_na$Median.ACT)

scatter.smooth(college_ds_no_na$Est..price.2019.20.with.avg..grant, college_ds_no_na$Median.SAT)
scatter.smooth(college_ds_no_na$Est..price.2019.20.with.avg..grant, college_ds_no_na$Median.ACT)
cor(college_ds_no_na$Est..price.2019.20.with.avg..grant, college_ds_no_na$Median.SAT)
cor(college_ds_no_na$Est..price.2019.20.with.avg..grant, college_ds_no_na$Median.ACT)


scatter.smooth(college_ds_no_na$Est_avg_price, college_ds_no_na$X..of.students.who.get.any.grants)
cor(college_ds_no_na$Est_avg_price, college_ds_no_na$X..of.students.who.get.any.grants)

# 0.3689321
scatter.smooth(log(college_ds$Est_grant), (college_ds$Early.career.earnings))
cor(log(college_ds$Est_grant), (college_ds$Early.career.earnings))

get_score <- function(df) {
  score = df$Est_avg_price
}
```

```{r}
hist(college_ds$Early.career.earnings, xlab = "early career earnings (x $1000)", main = "Early career earnings")

hist(college_ds$Median.SAT, xlab = "SAT score", main = "SAT score")
hist(college_ds$Median.ACT, xlab = "ACT score", main = "ACT score")
boxplot(college_ds$Early.career.earnings)
boxplot(college_ds$Median.SAT)
boxplot(college_ds$Median.ACT)
```

```{r}
private_college = subset(college_ds_no_na, is.public == 0)
cor(private_college$Median.ACT, private_college$Early.career.earnings)
cor(private_college$Median.SAT, private_college$Early.career.earnings)
hist(private_college$Early.career.earnings)
hist(private_college$Median.ACT)
hist(private_college$Median.SAT)
public_college = subset(college_ds_no_na, is.public == 1)
cor(public_college$Median.ACT, public_college$Early.career.earnings)
cor(public_college$Median.SAT, public_college$Early.career.earnings)
hist(public_college$Early.career.earnings)
hist(public_college$Median.ACT)
hist(public_college$Median.SAT)


```

```{r}
# Freq of private and public counterparts
hist_gen <- function(red, blue, x_lab, title) {
  x_bounds = c(min(min(red), min(blue)), max(max(red), max(blue)))
  blue_data = hist(blue, plot = FALSE)
  red_data = hist(red, plot = FALSE)
  y_bounds = c(min(min(blue_data$density), min(red_data$density)), max(max(blue_data$density), max(red_data$density)))
  print(sprintf("red sum: %f, blue sum: %f", sum(red_data$density), sum(blue_data$density)))
  plot(blue_data$mids, blue_data$density, xlim=x_bounds, ylim = y_bounds,
       xlab = x_lab, ylab = "probability", main = title, col = "blue", type = "l")
  par(new = TRUE)
  plot(red_data$mids, red_data$density, xlim = x_bounds, ylim = y_bounds,
       xlab = x_lab, ylab = "probability", main = title, col = "red", type = "l")
}
hist_gen(private_college$Median.SAT, public_college$Median.SAT, "SAT score", "public (blue) vs private (red) SAT req")
hist_gen(private_college$Median.ACT, public_college$Median.ACT, "ACT score", "public (blue) vs private (red) ACT req")
hist_gen(private_college$Early.career.earnings, public_college$Early.career.earnings, "Early career earning (x $1000)", "public (blue) vs private (red) ECE")
```

```{r}
plot(college_ds_no_na$Median.SAT, college_ds_no_na$Early.career.earnings, xlab = "Median SAT score", ylab = "Early career earning (* $10^4)")
par(new = FALSE)
pred_sat_ece = predict(lg.SAT_ece)
points(x = college_ds_no_na$Median.SAT, y = pred_sat_ece, type = "l", col = "red", xlab = "Median SAT score", ylab = "Early career earning (* $10^4)")

plot(college_ds_no_na$Median.SAT,resid(lg.SAT_ece), ylab = "residual", xlab = "MSAT", main = "Estimate residuals")

hist_gen(pred_sat_ece, college_ds_no_na$Early.career.earnings, x_lab = "ECE (x $1000)", "predicted (red) vs data (blue) ECE histogram")

# anova(lg.SAT_ece)
summary(lg.SAT_ece)
# anova(lg.ACT_ece)
hist(resid(lg.SAT_ece))
# t.test(resid(lg.SAT_ece),mu = 0, alternative = "t")
anova(lg.SAT_ece)

```

